FROM nginx:1.25-alpine
COPY dist/app /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY .nginx.conf /etc/nginx

# COPY ./index.html /usr/share/nginx/html/index.html
